name: attend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.0.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  share_plus: ^10.1.4
  csv: ^6.0.0
  provider: ^6.1.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
